"""made permission not null

Revision ID: 3938cd98c022
Revises: 4be1d87d5a99
Create Date: 2026-03-04 18:34:14.100063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3938cd98c022'
down_revision: Union[str, Sequence[str], None] = '4be1d87d5a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('permission',
               existing_type=sa.INTEGER(),
               server_default='0',
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('permission',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
