"""inital

Revision ID: 64db0791bdfc
Revises: 
Create Date: 2026-02-25 18:45:20.230238

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '64db0791bdfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
