"""Login support

Revision ID: a64819602a53
Revises: ccb3eee4786b
Create Date: 2026-02-25 19:55:40.864530

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a64819602a53'
down_revision: Union[str, Sequence[str], None] = 'ccb3eee4786b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
