"""changed name to username

Revision ID: d7a121c3b8bd
Revises: a64819602a53
Create Date: 2026-02-25 20:40:30.052185

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd7a121c3b8bd'
down_revision: Union[str, Sequence[str], None] = 'a64819602a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
